{{- if not .Values.github.existingSecret }}
# SPDX-FileCopyrightText: 2026 Robert Eggl <robert@eggl.dev>
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-deployment-bridge.secretName" . }}
  labels:
    {{- include "github-deployment-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-id: {{ required "github.appId or github.existingSecret is required" .Values.github.appId | quote }}
  installation-id: {{ required "github.installationId or github.existingSecret is required" .Values.github.installationId | quote }}
  private-key: |
{{ required "github.privateKey or github.existingSecret is required" .Values.github.privateKey | indent 4 }}
{{- end }}
